server:
  port: 8080

spring:
  application:
    name: demo-policy-service

app:
  version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always