apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-policy-config
  namespace: tfm-dev
  labels:
    app: demo-policy-service
    environment: dev
    project: tfm
data:
  SPRING_PROFILES_ACTIVE: "dev"
  APP_NAME: "demo-policy-service"
  APP_VERSION: "1.0.0"