apiVersion: v1
kind: Secret
metadata:
  name: demo-policy-secret
  namespace: tfm-dev
  labels:
    app: demo-policy-service
    environment: dev
    project: tfm
type: Opaque
stringData:
  DEMO_API_KEY: "poc-value-not-real"